# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS upb::upb upb::utf8_range upb::fastdecode upb::json upb::port upb::table upb::descriptor_upb_proto upb::reflection upb::textformat upb::mini_table_internal upb::mini_table upb::extension_registry upb::collections upb::protoc-gen-upb upb::protoc-gen-upbdefs)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target upb::upb
add_library(upb::upb STATIC IMPORTED)

set_target_properties(upb::upb PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "upb::extension_registry;upb::fastdecode;upb::port;upb::utf8_range"
)

# Create imported target upb::utf8_range
add_library(upb::utf8_range STATIC IMPORTED)

# Create imported target upb::fastdecode
add_library(upb::fastdecode STATIC IMPORTED)

set_target_properties(upb::fastdecode PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::extension_registry;upb::port;upb::table;upb::utf8_range"
)

# Create imported target upb::json
add_library(upb::json STATIC IMPORTED)

set_target_properties(upb::json PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::port;upb::reflection;upb::upb"
)

# Create imported target upb::port
add_library(upb::port INTERFACE IMPORTED)

# Create imported target upb::table
add_library(upb::table INTERFACE IMPORTED)

set_target_properties(upb::table PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::port"
)

# Create imported target upb::descriptor_upb_proto
add_library(upb::descriptor_upb_proto STATIC IMPORTED)

# Create imported target upb::reflection
add_library(upb::reflection STATIC IMPORTED)

set_target_properties(upb::reflection PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::collections;upb::descriptor_upb_proto;upb::mini_table;upb::port;upb::table;upb::upb"
)

# Create imported target upb::textformat
add_library(upb::textformat STATIC IMPORTED)

set_target_properties(upb::textformat PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::port;upb::reflection;upb::table"
)

# Create imported target upb::mini_table_internal
add_library(upb::mini_table_internal INTERFACE IMPORTED)

set_target_properties(upb::mini_table_internal PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::extension_registry;upb::port;upb::table;upb::upb"
)

# Create imported target upb::mini_table
add_library(upb::mini_table STATIC IMPORTED)

set_target_properties(upb::mini_table PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::extension_registry;upb::mini_table_internal;upb::port;upb::upb"
)

# Create imported target upb::extension_registry
add_library(upb::extension_registry STATIC IMPORTED)

set_target_properties(upb::extension_registry PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::port;upb::table"
)

# Create imported target upb::collections
add_library(upb::collections STATIC IMPORTED)

set_target_properties(upb::collections PROPERTIES
  INTERFACE_LINK_LIBRARIES "upb::descriptor_upb_proto;upb::mini_table;upb::port;upb::table;upb::upb"
)

# Create imported target upb::protoc-gen-upb
add_executable(upb::protoc-gen-upb IMPORTED)

# Create imported target upb::protoc-gen-upbdefs
add_executable(upb::protoc-gen-upbdefs IMPORTED)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/upb-config-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
